<?php
declare(strict_types=1);

// EnergyRadioStations SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

EnergyRadioStationsUtility::setRegistrar(function (EnergyRadioStationsUtility $u): void {
    $u->clean = [EnergyRadioStationsClean::class, 'call'];
    $u->done = [EnergyRadioStationsDone::class, 'call'];
    $u->make_error = [EnergyRadioStationsMakeError::class, 'call'];
    $u->feature_add = [EnergyRadioStationsFeatureAdd::class, 'call'];
    $u->feature_hook = [EnergyRadioStationsFeatureHook::class, 'call'];
    $u->feature_init = [EnergyRadioStationsFeatureInit::class, 'call'];
    $u->fetcher = [EnergyRadioStationsFetcher::class, 'call'];
    $u->make_fetch_def = [EnergyRadioStationsMakeFetchDef::class, 'call'];
    $u->make_context = [EnergyRadioStationsMakeContext::class, 'call'];
    $u->make_options = [EnergyRadioStationsMakeOptions::class, 'call'];
    $u->make_request = [EnergyRadioStationsMakeRequest::class, 'call'];
    $u->make_response = [EnergyRadioStationsMakeResponse::class, 'call'];
    $u->make_result = [EnergyRadioStationsMakeResult::class, 'call'];
    $u->make_point = [EnergyRadioStationsMakePoint::class, 'call'];
    $u->make_spec = [EnergyRadioStationsMakeSpec::class, 'call'];
    $u->make_url = [EnergyRadioStationsMakeUrl::class, 'call'];
    $u->param = [EnergyRadioStationsParam::class, 'call'];
    $u->prepare_auth = [EnergyRadioStationsPrepareAuth::class, 'call'];
    $u->prepare_body = [EnergyRadioStationsPrepareBody::class, 'call'];
    $u->prepare_headers = [EnergyRadioStationsPrepareHeaders::class, 'call'];
    $u->prepare_method = [EnergyRadioStationsPrepareMethod::class, 'call'];
    $u->prepare_params = [EnergyRadioStationsPrepareParams::class, 'call'];
    $u->prepare_path = [EnergyRadioStationsPreparePath::class, 'call'];
    $u->prepare_query = [EnergyRadioStationsPrepareQuery::class, 'call'];
    $u->graphql_body = [EnergyRadioStationsGraphql::class, 'body'];
    $u->graphql_errors = [EnergyRadioStationsGraphql::class, 'errors'];
    $u->result_basic = [EnergyRadioStationsResultBasic::class, 'call'];
    $u->result_body = [EnergyRadioStationsResultBody::class, 'call'];
    $u->result_headers = [EnergyRadioStationsResultHeaders::class, 'call'];
    $u->transform_request = [EnergyRadioStationsTransformRequest::class, 'call'];
    $u->transform_response = [EnergyRadioStationsTransformResponse::class, 'call'];
});
